name: Gradle unit tests

on:
  push:
    branches:
      - "add-unit-tests"
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/setup-gradle@v3

      - name: Run unit tests with Gradle
        run: ./gradlew test
